### PR TITLE
Added help for builder image.

### PR DESCRIPTION
**Pull request by iBobik**

### CODE REVIEW

**Comment by envygeeks** [comment]
:shipit: after the modification requests!

**Comment by iBobik** [comment]
Changed. You want to be swiss, I want to be more intuitive :-)

**Comment by envygeeks** [comment]
This image was designed for systems guy and programmers so I don't know if intuitive works here since we all have strong preferences and will just ignore what doesn't matter to us.  I prefer to stay Swiss on the topic because we all have strong preferences for deployment example: We use Travis CI and Bamboo, you use Gitlab.  You deploy with LFTP, I built this Docker image so people could deploy on my servers with Git and a backend build server watching.

There is a disparity in preference which forces me to remain neutral or alienate and I enforce that on some of my repos that are highly visible to support that stance too (but I always keep the Wiki open for all to contribute too.)

**Comment by iBobik** [comment]
Makes sense. :-)



Jan Pobořil

2015-10-19 0:24 GMT-05:00 Jordon Bedwell <notifications@github.com>:

**Pull request merged**
