### PR TITLE
Added bash, openssl-client, lftp and html-proofer

### PR DESCRIPTION
**Pull request by iBobik**
Useful utilities for CI building.

### CODE REVIEW

**Comment by envygeeks** [comment]
Please justify each package and change. Except for html-proofer.

**Comment by iBobik** [comment]
- bash: Required for GitLab CI (it's runner just needs it)
- lftp: Upload built site to static web server
- openssl-client: required by lftp for some protocols, but could be used by self

**Comment by envygeeks** [comment]
Can you provide the image sizes for me?

**Comment by iBobik** [comment]
Of course, for "latest" tag:
- before: 144 MB
- after: 153 MB

**Comment by envygeeks** [comment]
I'm gonna let this sit and think, that's a huge bump for something so tailored.  The most concerning part is the bash, I don't know if I'm willing to fix quirks in Gitlab CI (and to be honest I don't even know how or why it would "require bash" because you would have to launch Docker yourself -- unless there is something I am missing, but either way that is a bug in Gitlab.)

The other stuff is stuff that should really be done on the host system.

**Comment by envygeeks** [comment]
I will however compromise with you, create a gitlab tag and add all that stuff there and I'll happily merge it for you and support it, give you give me about 10 minutes I will create the capability for you to do such a thing.

**Comment by iBobik** [comment]
I understand. I already asked for this "feature" in it: https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/226

**Comment by iBobik** [comment]
So do you think it is better to maintain second tag for this use case?

Do you want to do it only because bash or for another things what could be useful? (deploy tools, remove nginx, ...)

**Comment by iBobik** [comment]
Btw, if you want, maybe it will be better to name tag "builder" or something like this, because it is not fixed only for this CI solution. "gitlab" tag is too specific.

**Comment by envygeeks** [comment]
I like `build-and-deploy`, but if we are gonna name it that, make sure to add git and rsync for other people, I've added a commit that creates a per-tag packages variable for you to add all those packages to, if you create a dedicated tag and rebase/cleanup-merge those commits I'll happily accept the pull!

**Comment by envygeeks** [comment]
Nah, `builder` is fine.  The dashes are annoying me kinda. Yeah builder is fine.

**Pull request closed without merging**
