### PR TITLE
Added help for builder tag.

### PR DESCRIPTION
**Pull request by iBobik**
What do you think about this formulation?

### CODE REVIEW

**Comment by envygeeks** [comment]
As this is written it's a :-1: our repo does not lend itself to promoting CI's, we do not lend ourself to deployment methods (even if we offer a builder image) because it's us who has to support that method or any questions about that CI if I accept this.  I am fine with describing the builder image and it's purpose (as long as it doesn't mention a specific CI or way to deploy) but I am not willing to support specific deployment methods.

**Comment by envygeeks** [comment]
I'm also going to reject this pull because you're pull request clearly overtakes my commit I already did with another message and puts it into your name, giving you credit for my work, that's not cool and I'm not down for that.

**Comment by iBobik** [comment]
It is not ok to provide example how it can be used, including some
disclaimer?

Sorry about Pry, I added it there by mistake.



Jan Pobořil

2015-10-18 23:34 GMT-05:00 Jordon Bedwell <notifications@github.com>:

**Comment by envygeeks** [comment]
It is not, not in the readme at least.  Now, I am fine with a Wiki page dedicated to LFTP deployment under a larger "deployment" scope and then a modification to the readme that points to the broader deployment page which links to the LFTP deployment page.

**Pull request closed without merging**
