### PR TITLE
added rsync to the package list

### PR DESCRIPTION
**Pull request by NioTeX**

### CODE REVIEW

**Comment by envygeeks** [comment]
This should be done in `opts.yml` and then synced.

**Comment by NioTeX** [comment]
well, I'm not a ruby developer. I tried building the docker files with updated opts.yml, and got stuck here:
```bash
$ bundle exec docker-template jekyll:builder
Could not find command "jekyll:builder".
```

**Comment by envygeeks** [comment]
@NioTeX The documentation here is out of sync with the latest changes made a week ago upstream, you need to do: `bundle exec docker-template build jekyll --sync-only` after updating `opts.yml`

**Comment by NioTeX** [comment]
yeah, also tried with that. Getting an error, but just because I know some gems have errors on OS X El Capitan, I also tried in a ruby docker, `bundle install` good, but after `bundle exec docker-template build jekyll --sync-only` same error: 
```
/usr/local/bundle/bundler/gems/docker-template-5bda91ef4e31/lib/docker/template/metadata.rb:441:in `method_missing': undefined method `as_hash' for #<Docker::Template::Metadata:0x00559331e40150> (NoMethodError)
	from (erb):4:in `_binding'
	from /usr/local/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /usr/local/lib/ruby/2.3.0/erb.rb:864:in `result'
	from /usr/local/bundle/bundler/gems/docker-template-5bda91ef4e31/lib/docker/template/normal.rb:35:in `copy_dockerfile'
	from /usr/local/bundle/bundler/gems/docker-template-5bda91ef4e31/lib/docker/template/normal.rb:23:in `setup_context'
	from /usr/local/bundle/bundler/gems/docker-template-5bda91ef4e31/lib/docker/template/builder.rb:194:in `block in setup'
	from /usr/local/bundle/bundler/gems/docker-template-5bda91ef4e31/lib/docker/template/builder.rb:192:in `map'
	from /usr/local/bundle/bundler/gems/docker-template-5bda91ef4e31/lib/docker/template/builder.rb:192:in `setup'
	from /usr/local/bundle/bundler/gems/docker-template-5bda91ef4e31/lib/docker/template/builder.rb:127:in `build'
	from /usr/local/lib/ruby/2.3.0/set.rb:306:in `each_key'
	from /usr/local/lib/ruby/2.3.0/set.rb:306:in `each'
	from /usr/local/bundle/bundler/gems/docker-template-5bda91ef4e31/lib/docker/template/cli.rb:24:in `map'
	from /usr/local/bundle/bundler/gems/docker-template-5bda91ef4e31/lib/docker/template/cli.rb:24:in `block in build'
	from /usr/local/bundle/bundler/gems/docker-template-5bda91ef4e31/lib/docker/template/cli.rb:86:in `with_profiling'
	from /usr/local/bundle/bundler/gems/docker-template-5bda91ef4e31/lib/docker/template/cli.rb:23:in `build'
	from /usr/local/bundle/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/bundle/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/bundle/bundler/gems/docker-template-5bda91ef4e31/bin/docker-template:25:in `<top (required)>'
	from /usr/local/bundle/bin/docker-template:16:in `load'
	from /usr/local/bundle/bin/docker-template:16:in `<main>'
```

**Comment by envygeeks** [comment]
@NioTeX looks like you caught a bug in docker-template, can you repost this upstream at https://github.com/envygeeks/docker-template so I can resolve it in the morning.

**Comment by NioTeX** [comment]
I pushed my changes here: https://github.com/LynxSolutions/jekyll-docker/tree/error
could not push to master, since I already have GitlabCI using an automatically built image from my repository for building jekyll websites. If I push the error, my builds will fail :/

**Comment by envygeeks** [comment]
It seems this was resolved by another commit and I'll double check it's on the list tonight.

**Pull request closed without merging**
