### PR TITLE
Add link and description installed gems

### PR DESCRIPTION
**Pull request by iBobik**
It is good to have on eyes what they are good for.

Can I add it for all other gems?

### CODE REVIEW

**Comment by parkr** [comment]
Sure, feel free to link these up. Don't see why not.

**Comment by envygeeks** [comment]
I'm okay with this, but lets keep the deep descriptions out of it, link to the Gems IMO because it's really the job of @jekyll/core to explain our dependencies and not our Docker image job to explain Jekyll's dependencies, but linking to the gem on RubyGem is a good idea.

On therubyracer... we don't use that anymore because it has problems with muslc, we use NodeJS by default on all our images so I should probably remove that from our list even if it could be accidentally installed by way of a "gem install" on soon to be old-stable Jekyll (2.5)

**Comment by iBobik** [comment]
I thing it is more useable to link gem's homepage (usually Github repo), because there are much more info than on rubygems.org.

And about description, is it problem to have it there? It is not competence of Docker image, but it could be helpful to users of Docker image.

**Comment by envygeeks** [comment]
Yes it's a problem, like I said, it's not our job to explain Jekyll's dependencies, it's Jekyll's job and even though this is an official Jekyll project, it is not Core which these depends belog. Those dependencies are not ours therefore it is not our job to explain them and most Rubyist will know exactly what each of those gems are because each one of those gems has a high exposure.

It's much less useful to point them to a Github repository too, just like with System packages it's more beneficial to link people to a page that gives everything a user needs to know (if you link me to a repository I have the same problem you are trying to solve here, what are the dependencies of my dependencies?)  And RubyGem's will link to the source page, it has a button that both points to the main home page and the source page (unless both are the same.)

**Comment by envygeeks** [comment]
I would much prefer there to simply be a link, over crufting our `README.md`  If need be and you really want this then lets create an official Docker page on the Jekyll site and do all that properly and link to it from our README.

**Comment by envygeeks** [comment]
Well that is if it's fine with @parkr since that's his territory.

**Comment by envygeeks** [comment]
Let me elaborate why I am so against it, because I feel like I am being resistant without a reason: Our dependencies are a moving target.  I might drop one one day, that means if I move a dependency in favor of a more stable dependency because our servers and build servers report less problems building with that dependency I have to backtrack and add a new description.  This makes it hard to maintain and adds more points I need to care about to keep this image as fast moving as it is.

**Comment by iBobik** [comment]
Now I understand :-)

So how about to remove all Jekyll mandatory dependencies and put there just
link „All Jekyll dependencies” to page where they are described? Optional
gems should be described there.

Users of Jekyll are not always Ruby devs (like me), so it makes sense to
describe it.

What exactly is at rubygems.org useful for this use-case? For me just one
sentence what it does. The same sentence I want to copy there. More
information are at it’s homepage.



Jan Pobořil

2015-10-25 15:31 GMT-05:00 Jordon Bedwell <notifications@github.com>:

**Comment by envygeeks** [comment]
RubyGems.org provides the owners description, a link to the home page, a link to the version we use, a link to the source, all of it's dependencies (if you are doing an audit which is important.) And it provides the sums that most authors do not provide for their own gems.  In general the preference (just like I would do with say an Ubuntu package) would be to link to those pages which will direct you to the more relevant pages but give you a high level overview of everything it relies on.

**Comment by iBobik** [comment]
Ok.

How about to remove Jekyll mandatory dependencies and just provide link to
page where they are listed?



Jan Pobořil

2015-10-25 15:52 GMT-05:00 Jordon Bedwell <notifications@github.com>:

**Comment by envygeeks** [comment]
I don't like the idea but that's an acceptable compromise.  I do not know if Jekyll has an official page (I honestly have never even looked at the site because I browse the source to get my answers or just message @parkr directly.)  But if there isn't one, you can certainly ask for one on `jekyll/jekyll` repo and I don't reckon there would be much trouble getting the idea accepted.

**Comment by iBobik** [comment]
I also did not found page describing dependencies of Jekyll. So @parkr, how
about to add section there?
http://jekyllrb.com/docs/plugins/



Jan Pobořil

2015-10-25 16:23 GMT-05:00 Jordon Bedwell <notifications@github.com>:

**Comment by envygeeks** [comment]
You need file that ticket on `jekyll/jekyll` instead of asking him to do it from here, the preference for Documentation on Jekyll is also to just send a pull request where you see fit and ask for review: https://github.com/jekyll/jekyll

**Comment by iBobik** [comment]
Asked: jekyll/jekyll#4054

**Comment by envygeeks** [comment]
I'm okay with this now @iBobik go ahead and link them up and update the pull request if you want and one of us will merge it.  After a long thought I think you are right that it will be helpful, however please make them referenced links please!

**Comment by iBobik** [comment]
Why referenced links? It will move away mess from the list, but will create
another mess (one list with names and second with addreses), because
related thinks will not be together. References are good for keeping
sentences readable, but there are not sentences, just list of names.



Jan Pobořil

2015-11-23 1:29 GMT-06:00 Jordon Bedwell <notifications@github.com>:

**Comment by envygeeks** [comment]
That's a subjective assessment of what a mess is and it's an irrelevant debate.

**Comment by iBobik** [comment]
Done.

**Comment by iBobik** [comment]
Thanks.



Jan Pobořil

2015-11-23 22:26 GMT-06:00 Jordon Bedwell <notifications@github.com>:

**Pull request merged**
